# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MonitorTime2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AvoidCrash', '~> 2.5.2'
  
pod 'MLeaksFinder'

  # Pods for MonitorTime2

end
