# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MonitorTimer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'JLRoutes', '~> 2.1' #路由库

end
